### ISSUE TITLE
Support generating Rust bindings.

### ISSUE THREAD

**Issue by eddyb** [radare/valabind#20]
I believe this would be a great addition to the Rust community, considering that high-level Vala maps well to safe Rust code, while the VAPIs provide enough information for binding the raw C APIs from Rust.

**Comment by radare** [comment]
@eddyb ping

**Comment by eddyb** [comment]
I've given up on this, sorry, most people use [`bindgen`](https://github.com/rust-lang-nursery/rust-bindgen).
