### ISSUE TITLE
CTypes problem with dependencies

### ISSUE THREAD

**Issue by simonzack** [radare/valabind#23]
Only one library is loaded in the generated ctypes code regardless of how many dependencies there are, e.g. `r_asm` depends on `r_utils` but only `lib = CDLL (find_library ('r_asm'))` is used.
This causes AttributeErrors when the module is imported into python:
`AttributeError: function 'r_strbuf_set' not found`

**Comment by radare** [comment]
i fixed this already, ctypes work fine now
