### ISSUE TITLE
Error when compiling dlangwriter.vala and cxxwriter.vala using vala development version(Vala 0.35.3.10-6b27)

### ISSUE THREAD

**Issue by dnivra** [radare/valabind#39]
When I try to build valabind by following the steps listed [radare2-bindings README](https://github.com/radare/radare2-bindings/blob/master/README.md#dependencies), I get the following error:

``` bash
Compiling config.vala main.vala valabindwriter.vala nodeffiwriter.vala utils.vala girwriter.vala swigwriter.vala cxxwriter.vala ctypeswriter.vala dlangwriter.vala gowriter.vala -> valabind
valac -g --cc="cc"  -o valabind --pkg posix --pkg libvala-0.36 --save-temps  config.vala main.vala valabindwriter.vala nodeffiwriter.vala utils.vala girwriter.vala swigwriter.vala cxxwriter.vala ctypeswriter.vala dlangwriter.vala gowriter.vala 

dlangwriter.vala:170.7-170.17: error: The name `get_ctype' does not exist in the context of `Vala.Field'
		if (f.get_ctype () == null) {
		    ^^^^^^^^^^^
cxxwriter.vala:160.7-160.17: error: The name `get_ctype' does not exist in the context of `Vala.Field'
		if (f.get_ctype () == null) {
```

# Environment details

OS: Ubuntu 16.04.1

valabind commit: [dafdaf4](https://github.com/radare/valabind/commit/dafdaf43fb69750663a44fdb3d4f141a1943e28a)

vala commit: [6b275cf](https://git.gnome.org/browse/vala/commit/?id=6b275cf3adcdae1b91054586435d10c99d13c0ef)

Building valabind with vala 0.34.4 succeeds with 3 warnings so not sure if it's valabind's or vala's issue. Is it fine to build valabind using stable vala rather than the latest available from git? radare2-binding's README explicitly has a step of building vala dev using vala stable so thought I'd ask.

**Comment by radare** [comment]
Build with latest stable vala. Ill take care of this bug when the api change version of vala gets released. Feel free to submit a patch to fix this if you know the change
