### ISSUE TITLE
meson: File config.vala does not exist

### ISSUE THREAD

**Issue by jbicha** [radare/valabind#42]
I tried using meson to compile valabind 1.4.0 but `meson.build` lists `config.vala` as a file but that file isn't provided or built by meson.

**Comment by eddyb** [comment]
For the record, this is how `Makefile` does it: https://github.com/radare/valabind/blob/f0fb63266a8791ad2074adc0864eaee2e3b65f77/Makefile#L70-L72

**Comment by radare** [comment]
Fixed in b56c82d3b8acaa4b0942b6248e4c4c15624ba3a1

thanks
