### ISSUE TITLE
 fatal error: sys/wait.h: No such file or directory

### ISSUE THREAD

**Issue by kuh3h3** [radare/valabind#44]
tries to build on windows 10 msys2, mingw64, but failed

nodeffiwriter.c:588:12: warning: unknown escape sequence: '\m'
nodeffiwriter.c:588:12: warning: unknown escape sequence: '\s'
C:msys64mingw64share/vala-0.36/vapi/glib-2.0.vapi:1412:12: warning: unknown escape sequence: '\m'
C:msys64mingw64share/vala-0.36/vapi/glib-2.0.vapi:1412:12: warning: unknown escape sequence: '\m'
C:msys64mingw64share/vala-0.36/vapi/glib-2.0.vapi:1412:12: warning: unknown escape sequence: '\s'
C:msys64mingw64share/vala-0.36/vapi/glib-2.0.vapi:1412:12: warning: unknown escape sequence: '\m'
C:msys64mingw64share/vala-0.36/vapi/glib-2.0.vapi:1412:12: warning: unknown escape sequence: '\m'
C:msys64mingw64share/vala-0.36/vapi/glib-2.0.vapi:1412:12: warning: unknown escape sequence: '\s'
C:msys64mingw64share/vala-0.36/vapi/glib-2.0.vapi:1412:12: warning: unknown escape sequence: '\m'
C:msys64mingw64share/vala-0.36/vapi/glib-2.0.vapi:1412:12: warning: unknown escape sequence: '\m'
C:msys64mingw64share/vala-0.36/vapi/glib-2.0.vapi:1412:12: warning: unknown escape sequence: '\s'
C:/msys64/home/kuh3h3/valabind/utils.c:14:10: fatal error: sys/wait.h: No such file or directory
 #include <sys/wait.h>
          ^~~~~~~~~~~~
compilation terminated.

----

Compilation failed: 1 error(s), 0 warning(s)
error: cc exited with status 1
make: *** [Makefile:62: valabind] Errror 1

kuh3h3@DESKTOP-R0PM5LB MINGW64 ~/valabind
$ valac --version
Vala 0.36.4-dirty

**Comment by radare** [comment]
that code is generated from glib-2.0.vapi, so this is not an issue in valabind, but in vala or in glib

**Comment by kuh3h3** [comment]
Is this Msys2 and mingw64 environ inherit problems?
I didn`t set  MSYS2_PATH_TYPE.
but  msys2 have only mingw64 vala package.
so how msys2 can use mingw64 valac?
so weird situation.
in msys2 shell, can`t use mingw64 valac.
in mingw64 shell, can`t include   sys/wait.h

**Comment by radare** [comment]
dunno, but this seems like an issue in mingw not in r2 or valabind or vala
