### ISSUE TITLE
Port valabind to non-dead language

### ISSUE THREAD

**Issue by XVilka** [radare/valabind#45]
See https://www.bassi.io/articles/2017/02/13/on-vala/

**Comment by XVilka** [comment]
See also https://blogs.gnome.org/mcatanzaro/2017/02/19/on-problems-with-vala/

**Comment by XVilka** [comment]
Maybe extending something like https://github.com/rust-lang-nursery/rust-bindgen makes more sense

**Comment by radare** [comment]
according to the vala developers vala is not ded. closing this issue, feel free to make your own bindings generator and put it (or use it) in radare2-regressions, but this issue doesnt belongs to valabind
