### ISSUE TITLE
Makefile: unable to find --pkg valacodegen-0.40

### ISSUE THREAD

**Issue by blshkv** [radare/valabind#47]
Hi, I'm trying to compile valabind 1.5.0 it fails with the following error:
```
Compiling config.vala main.vala valabindwriter.vala nodeffiwriter.vala utils.vala girwriter.vala swigwriter.vala cxxwriter.vala ctypeswriter.vala dlangwriter.vala gowriter.vala -> valabind
"valac-0.36" -o valabind --pkg posix --pkg libvala-0.36 --save-temps  config.vala main.vala valabindwriter.vala nodeffiwriter.vala utils.vala girwriter.vala swigwriter.vala cxxwriter.vala ctypeswriter.vala dlangwriter.vala gowriter.vala 
swigwriter.vala:25.24-25.54: error: The name `get_ccode_header_filenames' does not exist in the context of `Vala'
                foreach (string i in Vala.get_ccode_header_filenames (s).split (",")) {
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
swigwriter.vala:197.15-197.33: error: The name `get_ccode_name' does not exist in the context of `Vala'
                var cname = Vala.get_ccode_name (c);
                            ^^^^^^^^^^^^^^^^^^^
swigwriter.vala:197.7-197.37: error: var declaration not allowed with non-typed initializer
                var cname = Vala.get_ccode_name (c);
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I have dev-lang/vala-0.36.7 installed but I can't figure out where valacodegen-0.40 should come from.
Any hints?

Thank you

**Comment by blshkv** [comment]
Gr.. it looks like this is a dup of https://github.com/radare/valabind/issues/43

**Comment by blshkv** [comment]
Ok, so from what I understood, the release v1.5.0 is broken.

The stable release should be compiled against stable dependencies (vala) but they have not released 0.40 yet.

**Comment by radare** [comment]
All previous releases of valabind are broken for vala <0.40 So use an older version of vala or wait until new vala is released. I cant fix broken vala releases from here

**Comment by radare** [comment]
cant fix this because there's no way to make valabind build with old versions of vala. use vala-unstable or vala-git, or wait for a new release.

**Comment by radare** [comment]
I tagged master, so you may be able to get the 1.6 tarball of valabind

**Comment by anthraxx** [comment]
thx a lot, as always: best stuff. Thumbs

**Comment by radare** [comment]
👍
