### ISSUE TITLE
Missing rpath for libvalaccodegen.so

### ISSUE THREAD

**Issue by bartoszek** [radare/valabind#48]
Current `Makefile` is missing rpath for correctly resolving  `libvalaccodegen`.

`ldd /usr/bin/valabind`
```
        linux-vdso.so.1 (0x00007ffc7ffce000)
        libvala-0.40.so.0 => /usr/lib/libvala-0.40.so.0 (0x00007f73cfeee000)
        libgobject-2.0.so.0 => /usr/lib/libgobject-2.0.so.0 (0x00007f73cfc9a000)
        libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007f73cf983000)
        libvalaccodegen.so => not found
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f73cf5cc000)
        libgmodule-2.0.so.0 => /usr/lib/libgmodule-2.0.so.0 (0x00007f73cf3c8000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f73cf1aa000)
        libffi.so.6 => /usr/lib/libffi.so.6 (0x00007f73cefa1000)
        libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007f73ced2e000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f73d04c7000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f73ceb2a000)
```

[rpath.patch.txt](https://github.com/radare/valabind/files/1891524/rpath.patch.txt)

**Comment by radare** [comment]
Why dont you send a pullreq?

**Comment by bartoszek** [comment]
Normally I would, but your repo is configured so others can't edit and create pull request without forking ;(

**Comment by radare** [comment]
All pullreqs work the same way. You can even click in the pencil button. If you dont have commit access you cant create branches in this repo. Which is how the whole github thing works

**Comment by bartoszek** [comment]
Now it's working fine, must be something with my browser...

**Comment by radare** [comment]
and the PR?

**Comment by radare** [comment]
i did the pr and merged it https://github.com/radare/valabind/pull/49
