### ISSUE TITLE
Vala compiler automatic selection

### ISSUE THREAD

**Issue by XVilka** [radare/valabind#5]
On Gentoo systems, you can have multiple versions of vala installed, so they are:
/usr/bin/valac-0.12 
/usr/bin/valac-0.14
/usr/bin/valac-0.16
And have no "generic" /usr/bin/valac at all, even symlink is missing.
Right now I'm always recreate symlink in ebuild, but this is a wrong way. Please, add support for automatic finding latest proper vala compiler in valabind build system

**Comment by radare** [comment]
getvv does that, honors the version of vala linked to the first valac found in $PATH. you can also override the valac binary name with the VALAC env var

im assuming this is fine for everyone, if not please let me know
