### ISSUE TITLE
valabind d binding: Error: undefined identifier g_object_unref

### ISSUE THREAD

**Issue by JumpLink** [radare/valabind#8]
The binding generator using swig are working and can be compiled, valabinds own generator (not using swig) is generated but can't be compiled, it's thrown this error:  `Error: undefined identifier g_object_unref`
This is the way I try to generate the binding: https://github.com/JumpLink/vala-object/blob/master/valabind/dlang/Makefile#L11

This is the generated binding: http://paste.ubuntu.com/5862928/

**Comment by radare** [comment]
closing, no feedback after 5 years
